version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www
    networks:
      - laravel-network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:generated_app_key
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=root
      - DB_USERNAME=root
      - DB_PASSWORD=root

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
